apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  template:
    metadata:     
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:{{ .Values.mongodb.tag }}
        ports:
        - containerPort: 27017
        # resources:
        #   requests:
        #     cpu: "15m"
        #     memory: "500m"
        #   limits:
        #     cpu: "500m"
        #     memory: "500Gi"
        envFrom:
          {{- if empty .Values.mongodb.existSecret }}
          - secretRef:
              name: {{ .Release.Name }}-mongodb-secret
          {{- else }}
          - secretRef:
              name: {{ .Values.mongodb.existSecret }}
          {{- end }}
